# Generated by Django 2.2.1 on 2019-07-21 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
